# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Chess-Coverage
version:      0.0201
version_from: lib/Games/Chess/Coverage.pm
installdirs:  site
requires:
    Chess::PGN::Filter:            0.13
    Games::Chess:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
