#!/usr/bin/perl
use strict;
use warnings;
use Games::Chess::Coverage;
use Games::Chess::Coverage::SVG;
 
my $v = shift || 0;

my $cover = Games::Chess::Coverage->new(
    verbose => $v,
);
if( 0 and $v ) {
    warn $cover->whoami($_), "\n"
        for sort keys %{ $cover->pieces };
    warn "----\n";
}

my $drawing = Games::Chess::Coverage::SVG->new(
    verbose => $v,
    coverage => $cover,
    out_file => $0,
    image_type => 'svg',
);
#use Data::Dumper;warn Dumper(\$drawing);
warn $cover->game->to_text, "\n" if $v;

$drawing->add_rule( 'Games::Chess::Coverage::SVG::Board',
    board_color  => 'white', #[255,255,255],
    border       => 2,
    border_color => 'black', #[0,0,0],
    letters      => 1,
    letter_color => 'blue', #[0,0,255],
    grid         => 1,
    grid_color   => 'gray', #[127,127,127],
);

#$drawing->add_rule( 'SVGPieces' );
#$drawing->add_rule( 'Games::Chess::Coverage::SVG::Move',
#    white_move_color => '#33FF33',
#    black_move_color => '#00FFCC',
#    both_move_color  => '#FF6666',
#);
#$drawing->add_rule( 'Games::Chess::Coverage::SVG::Threat',
#    white_threat_color => '#000066',
#    black_threat_color => '#CC0033',
#);

$drawing->draw;
$drawing->write;
